services:
  - type: web
    name: thermalai-backend
    env: docker
    dockerfilePath: Dockerfile
    plan: standard
    autoDeploy: false
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.18
      - key: MODEL_GDRIVE_URL
        value: https://dl.fbaipublicfiles.com/segment_anything/sam_vit_h_4b8939.pth
